version: '3'

services:

  redis:
    container_name: redis_app
    image: redis
    ports:
      - "6379:6379"

  backend:
    container_name: backend_app
    build:
      context: ./backend
      dockerfile: Dockerfile
    # command: gunicorn djangoTestStripe.wsgi:application -w 4 --bind 0.0.0.0:8000
    command: bash start_app.sh
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  nginx:
    container_name: nginx_app
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  postgres:
    container_name: postgres_app
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

